version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
  disable:
    - depguard

linters-settings:
  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: imports-blacklist
      - name: indent-error-flow
      - name: range

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
