# This workflow builds and tests the module with the Go toolchain specified in go.mod.
# It keeps CI aligned with the module's declared toolchain so that version mismatches
# do not break dependency resolution.
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
