name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  golangci:
    runs-on: ubuntu-latest
    env:
      # Force using the toolchain declared by go.mod during both install and run
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Install golangci-lint v2 with project toolchain
        run: |
          set -euo pipefail
          echo "Using Go: $(go version)"
          # Ensure GOPATH/bin is on PATH for subsequent steps
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
          # Build golangci-lint from source using the toolchain configured above
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
          golangci-lint version
      - name: Run golangci-lint
        run: |
          set -euo pipefail
          golangci-lint run --timeout=5m
